# Generated by Django 6.0.3 on 2026-04-14 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoSimulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cargo de Simulação',
                'verbose_name_plural': 'Cargos de Simulação',
                'db_table': 'cargo_simulacao',
            },
        ),
        migrations.CreateModel(
            name='StatusCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_status', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Status do Ciclo',
                'verbose_name_plural': 'Status dos Ciclos',
                'db_table': 'status_ciclo',
            },
        ),
        migrations.CreateModel(
            name='CicloSimulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_edicao', models.CharField(max_length=150)),
                ('semestre', models.PositiveSmallIntegerField()),
                ('ano', models.PositiveSmallIntegerField()),
                ('periodo', models.CharField(blank=True, max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_coordenados', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(blank=True, db_table='participante_ciclo', related_name='ciclos_participados', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(db_column='id_status_ciclo', on_delete=django.db.models.deletion.PROTECT, related_name='ciclos', to='ciclos.statusciclo')),
            ],
            options={
                'verbose_name': 'Ciclo de Simulação',
                'verbose_name_plural': 'Ciclos de Simulação',
                'db_table': 'ciclo_simulacao',
            },
        ),
        migrations.CreateModel(
            name='GrupoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cargo_simulacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='ciclos.cargosimulacao')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='ciclos.ciclosimulacao')),
                ('membros', models.ManyToManyField(blank=True, db_table='membro_grupo', related_name='grupos_trabalho', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo de Trabalho',
                'verbose_name_plural': 'Grupos de Trabalho',
                'db_table': 'grupo_trabalho',
            },
        ),
    ]
