# Generated by Django 6.0.3 on 2026-04-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciclos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupotrabalho',
            old_name='cargo_simulacao',
            new_name='cargo',
        ),
    ]
