# Generated by Django 6.0.3 on 2026-04-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciclos', '0002_rename_cargo_simulacao_grupotrabalho_cargo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupotrabalho',
            old_name='cargo',
            new_name='cargo_simulacao',
        ),
    ]
