# Generated by Django 6.0.3 on 2026-04-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclos', '0003_rename_cargo_grupotrabalho_cargo_simulacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargosimulacao',
            name='cod',
            field=models.CharField(default='cod', max_length=20, unique=True, verbose_name='Código do Cargo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cargosimulacao',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Cargo Simulação'),
        ),
    ]
