# Generated by Django 6.0.3 on 2026-05-13 15:25
#
# The database was created from the SQL script (script_db_v2.6.sql), so the
# schema already matches the target state.  All operations are state-only.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclos', '0005_rename_gabinete_to_juiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='ciclosimulacao',
                    name='coordenador',
                    field=models.ForeignKey(db_column='professor_id', on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_coordenados', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AlterField(
                    model_name='ciclosimulacao',
                    name='periodo',
                    field=models.IntegerField(),
                ),
                migrations.AlterField(
                    model_name='ciclosimulacao',
                    name='status',
                    field=models.ForeignKey(db_column='status_ciclo_id', on_delete=django.db.models.deletion.PROTECT, related_name='ciclos', to='ciclos.statusciclo'),
                ),
                migrations.RemoveField(
                    model_name='grupotrabalho',
                    name='membros',
                ),
                migrations.RemoveField(
                    model_name='ciclosimulacao',
                    name='participantes',
                ),
                migrations.CreateModel(
                    name='MembroGrupo',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciclos.grupotrabalho')),
                        ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'membro_grupo',
                        'unique_together': {('grupo', 'usuario')},
                    },
                ),
                migrations.CreateModel(
                    name='ParticipanteCiclo',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciclos.ciclosimulacao')),
                        ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'participante_ciclo',
                        'unique_together': {('ciclo', 'usuario')},
                    },
                ),
                migrations.AddField(
                    model_name='grupotrabalho',
                    name='membros',
                    field=models.ManyToManyField(blank=True, related_name='grupos_trabalho', through='ciclos.MembroGrupo', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='ciclosimulacao',
                    name='participantes',
                    field=models.ManyToManyField(blank=True, related_name='ciclos_participados', through='ciclos.ParticipanteCiclo', to=settings.AUTH_USER_MODEL),
                ),
            ],
            database_operations=[],
        ),
    ]
