# Generated by Django 6.0.3 on 2026-05-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclos', '0007_fix_database_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclosimulacao',
            name='periodo',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
