# Generated by Django 6.0.8 on 2026-09-14 13:12

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclos', '0009_fix_coordenador_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ciclosimulacao',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome_edicao'), name='uniq_ciclo_nome_edicao_ci', violation_error_message='Já existe um ciclo com esse nome.'),
        ),
        migrations.AddConstraint(
            model_name='grupotrabalho',
            constraint=models.UniqueConstraint(models.F('ciclo'), django.db.models.functions.text.Lower('nome'), name='uniq_grupo_nome_por_ciclo_ci', violation_error_message='Já existe um grupo com esse nome neste ciclo.'),
        ),
    ]
