# Generated by Django 6.0.4 on 2026-04-29 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciclos', '0004_cargosimulacao_cod_alter_cargosimulacao_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseProcessual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Classe Processual',
                'verbose_name_plural': 'Classes Processuais',
                'db_table': 'classe_processual',
            },
        ),
        migrations.CreateModel(
            name='Comarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Comarca',
                'verbose_name_plural': 'Comarcas',
                'db_table': 'comarca',
            },
        ),
        migrations.CreateModel(
            name='ParteFicticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razao', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True)),
                ('tipo_pessoa', models.CharField(choices=[('Física', 'Física'), ('Jurídica', 'Jurídica')], max_length=10)),
            ],
            options={
                'verbose_name': 'Parte Fictícia',
                'verbose_name_plural': 'Partes Fictícias',
                'db_table': 'parte_ficticia',
            },
        ),
        migrations.CreateModel(
            name='StatusProcessoJudicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_status', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Status do Processo Judicial',
                'verbose_name_plural': 'Status dos Processos Judiciais',
                'db_table': 'status_processo_judicial',
            },
        ),
        migrations.CreateModel(
            name='TipoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Tipo de Processo',
                'verbose_name_plural': 'Tipos de Processo',
                'db_table': 'tipo_processo',
            },
        ),
        migrations.CreateModel(
            name='ProcessoJudicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('valor_causa', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15)),
                ('segredo_justica', models.BooleanField(default=False)),
                ('data_autuacao', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='ciclos.ciclosimulacao')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='processos.classeprocessual')),
                ('status_atual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='processos.statusprocessojudicial')),
                ('tipo_processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='processos.tipoprocesso')),
            ],
            options={
                'verbose_name': 'Processo Judicial',
                'verbose_name_plural': 'Processos Judiciais',
                'db_table': 'processo_judicial',
            },
        ),
        migrations.CreateModel(
            name='PoloProcessual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_polo', models.CharField(choices=[('Ativo', 'Ativo'), ('Passivo', 'Passivo'), ('Terceiro', 'Terceiro')], max_length=10)),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polos', to='processos.parteficticia')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polos', to='processos.processojudicial')),
            ],
            options={
                'verbose_name': 'Polo Processual',
                'verbose_name_plural': 'Polos Processuais',
                'db_table': 'polo_processual',
            },
        ),
        migrations.CreateModel(
            name='VaraServentia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('comarca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='varas', to='processos.comarca')),
            ],
            options={
                'verbose_name': 'Vara / Serventia',
                'verbose_name_plural': 'Varas / Serventias',
                'db_table': 'vara_serventia',
            },
        ),
        migrations.AddField(
            model_name='processojudicial',
            name='vara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='processos.varaserventia'),
        ),
    ]
