# Generated by Django 6.0.3 on 2026-04-23 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciclos', '0004_cargosimulacao_cod_alter_cargosimulacao_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseProcessual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Classe Processual',
                'verbose_name_plural': 'Classes Processuais',
                'db_table': 'classe_processual',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Comarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Comarca',
                'verbose_name_plural': 'Comarcas',
                'db_table': 'comarca',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ParteFicticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razao', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True)),
                ('tipo_pessoa', models.CharField(choices=[('Física', 'Física'), ('Jurídica', 'Jurídica')], max_length=8)),
            ],
            options={
                'verbose_name': 'Parte Fictícia',
                'verbose_name_plural': 'Partes Fictícias',
                'db_table': 'parte_ficticia',
                'ordering': ['nome_razao'],
            },
        ),
        migrations.CreateModel(
            name='StatusAudiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_status_audiencia', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Status de Audiência',
                'verbose_name_plural': 'Status de Audiências',
                'db_table': 'status_audiencia',
            },
        ),
        migrations.CreateModel(
            name='StatusProcessoJudicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_status', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Status do Processo',
                'verbose_name_plural': 'Status dos Processos',
                'db_table': 'status_processo_judicial',
            },
        ),
        migrations.CreateModel(
            name='TipoAudiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_audiencia', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Tipo de Audiência',
                'verbose_name_plural': 'Tipos de Audiência',
                'db_table': 'tipo_audiencia',
                'ordering': ['nome_audiencia'],
            },
        ),
        migrations.CreateModel(
            name='TipoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Tipo de Processo',
                'verbose_name_plural': 'Tipos de Processo',
                'db_table': 'tipo_processo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PoloProcessual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_polo', models.CharField(choices=[('Ativo', 'Ativo'), ('Passivo', 'Passivo'), ('Terceiro', 'Terceiro')], max_length=8)),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polos', to='processos.parteficticia')),
            ],
            options={
                'verbose_name': 'Polo Processual',
                'verbose_name_plural': 'Polos Processuais',
                'db_table': 'polo_processual',
            },
        ),
        migrations.CreateModel(
            name='ProcessoJudicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('valor_causa', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=15, null=True)),
                ('segredo_justica', models.BooleanField(default=False)),
                ('data_autuacao', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='ciclos.ciclosimulacao')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='processos.classeprocessual')),
                ('grupos', models.ManyToManyField(blank=True, db_table='grupo_processo', related_name='processos', to='ciclos.grupotrabalho')),
                ('partes', models.ManyToManyField(blank=True, related_name='processos', through='processos.PoloProcessual', to='processos.parteficticia')),
                ('status_atual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='processos.statusprocessojudicial')),
                ('tipo_processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='processos.tipoprocesso')),
            ],
            options={
                'verbose_name': 'Processo Judicial',
                'verbose_name_plural': 'Processos Judiciais',
                'db_table': 'processo_judicial',
                'ordering': ['-data_autuacao'],
            },
        ),
        migrations.AddField(
            model_name='poloprocessual',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polos', to='processos.processojudicial'),
        ),
        migrations.CreateModel(
            name='Audiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('link_sala_virtual', models.CharField(blank=True, max_length=255, null=True)),
                ('data_hora_realizacao', models.DateTimeField(blank=True, null=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiencias', to='processos.processojudicial')),
                ('status_audiencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audiencias', to='processos.statusaudiencia')),
                ('tipo_audiencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audiencias', to='processos.tipoaudiencia')),
            ],
            options={
                'verbose_name': 'Audiência',
                'verbose_name_plural': 'Audiências',
                'db_table': 'audiencia',
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='VaraServentia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('comarca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='varas', to='processos.comarca')),
            ],
            options={
                'verbose_name': 'Vara / Serventia',
                'verbose_name_plural': 'Varas / Serventias',
                'db_table': 'vara_serventia',
                'ordering': ['comarca__nome', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='processojudicial',
            name='vara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='processos.varaserventia'),
        ),
        migrations.AddConstraint(
            model_name='poloprocessual',
            constraint=models.UniqueConstraint(fields=('processo', 'parte', 'tipo_polo'), name='unique_polo_por_processo_e_parte'),
        ),
    ]
