# Generated by Django 6.0.4 on 2026-04-30 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclos', '0004_cargosimulacao_cod_alter_cargosimulacao_nome'),
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_processos', to='ciclos.grupotrabalho')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_processos', to='processos.processojudicial')),
            ],
            options={
                'verbose_name': 'Grupo do Processo',
                'verbose_name_plural': 'Grupos dos Processos',
                'db_table': 'grupo_processo',
            },
        ),
    ]
