# Generated by Django 6.0.4 on 2026-05-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processojudicial',
            name='valor_causa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
