# Generated by Django 6.0.4 on 2026-04-30 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclos', '0004_cargosimulacao_cod_alter_cargosimulacao_nome'),
        ('processos', '0002_grupoprocesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoprocesso',
            name='grupo',
            field=models.ForeignKey(db_column='grupotrabalho_id', on_delete=django.db.models.deletion.CASCADE, related_name='grupo_processos', to='ciclos.grupotrabalho'),
        ),
    ]
