# Generated by Django 6.0.4 on 2026-05-08 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclos', '0004_cargosimulacao_cod_alter_cargosimulacao_nome'),
        ('processos', '0002_alter_processojudicial_valor_causa'),
    ]

    operations = [
        migrations.AddField(
            model_name='processojudicial',
            name='grupo_atribuido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_atribuidos', to='ciclos.grupotrabalho'),
        ),
    ]
