# Generated by Django 6.0.3 on 2026-05-13 15:25
#
# The database was created from the SQL script (script_db_v2.6.sql), so most
# tables already exist.  Schema operations are state-only; only
# grupo_atribuido_id is conditionally dropped (it may have been added by
# migration 0003 on some environments).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_grupo_atribuido_if_exists(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE "
            "WHERE TABLE_SCHEMA = DATABASE() "
            "AND TABLE_NAME = 'processo_judicial' "
            "AND COLUMN_NAME = 'grupo_atribuido_id' "
            "AND REFERENCED_TABLE_NAME IS NOT NULL"
        )
        for (fk_name,) in cursor.fetchall():
            cursor.execute(
                "ALTER TABLE processo_judicial DROP FOREIGN KEY %s" % fk_name
            )
        cursor.execute(
            "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS "
            "WHERE TABLE_SCHEMA = DATABASE() "
            "AND TABLE_NAME = 'processo_judicial' "
            "AND COLUMN_NAME = 'grupo_atribuido_id'"
        )
        if cursor.fetchone()[0]:
            cursor.execute(
                "ALTER TABLE processo_judicial DROP COLUMN grupo_atribuido_id"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('ciclos', '0006_alter_ciclosimulacao_coordenador_and_more'),
        ('processos', '0003_processojudicial_grupo_atribuido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(drop_grupo_atribuido_if_exists, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='TipoMovimentacao',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('nome_movimentacao', models.CharField(max_length=45)),
                    ],
                    options={
                        'verbose_name': 'Tipo de Movimentação',
                        'verbose_name_plural': 'Tipos de Movimentação',
                        'db_table': 'tipo_movimentacao',
                    },
                ),
                migrations.RemoveField(
                    model_name='processojudicial',
                    name='grupo_atribuido',
                ),
                migrations.RemoveField(
                    model_name='processojudicial',
                    name='grupos',
                ),
                migrations.CreateModel(
                    name='GrupoProcesso',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciclos.grupotrabalho')),
                        ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.processojudicial')),
                    ],
                    options={
                        'db_table': 'grupo_processo',
                    },
                ),
                migrations.AddField(
                    model_name='processojudicial',
                    name='grupos',
                    field=models.ManyToManyField(blank=True, related_name='processos', through='processos.GrupoProcesso', to='ciclos.grupotrabalho'),
                ),
                migrations.CreateModel(
                    name='MovimentacaoProcessual',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('descricao_evento', models.TextField()),
                        ('data_movimento', models.DateTimeField(auto_now_add=True)),
                        ('antecedente_logico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consequentes', to='processos.movimentacaoprocessual')),
                        ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to=settings.AUTH_USER_MODEL)),
                        ('movimentacao_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_derivadas', to='processos.movimentacaoprocessual')),
                        ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='processos.processojudicial')),
                        ('tipo_movimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='processos.tipomovimentacao')),
                    ],
                    options={
                        'verbose_name': 'Movimentação Processual',
                        'verbose_name_plural': 'Movimentações Processuais',
                        'db_table': 'movimentacao_processual',
                        'ordering': ['-data_movimento'],
                    },
                ),
                migrations.CreateModel(
                    name='DocumentoAnexado',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('titulo_arquivo', models.CharField(max_length=150)),
                        ('caminho_arquivo', models.FileField(max_length=255, upload_to='documentos_processos/')),
                        ('data_upload', models.DateTimeField(auto_now_add=True)),
                        ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='processos.movimentacaoprocessual')),
                    ],
                    options={
                        'verbose_name': 'Documento Anexado',
                        'verbose_name_plural': 'Documentos Anexados',
                        'db_table': 'documento_anexado',
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
