# Generated by Django 6.0.4 on 2026-04-30 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_alter_grupoprocesso_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoprocesso',
            name='processo',
            field=models.ForeignKey(db_column='processojudicial_id', on_delete=django.db.models.deletion.CASCADE, related_name='grupo_processos', to='processos.processojudicial'),
        ),
    ]
