# Generated by Django 6.0.3 on 2026-05-18 15:52

import private_storage.fields
import private_storage.storage.files
import processos.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0006_create_movimentacao_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoanexado',
            name='caminho_arquivo',
            field=private_storage.fields.PrivateFileField(max_length=255, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=processos.models._upload_to_documento),
        ),
    ]
