# Generated by Django 6.0.4 on 2026-05-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0007_private_file_storage_por_processo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processojudicial',
            name='valor_causa',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=15, null=True),
        ),
    ]
