# Generated by Django 6.0.3 on 2026-05-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0008_alter_processojudicial_valor_causa'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenciaNumeroProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('tr', models.PositiveSmallIntegerField()),
                ('origem', models.PositiveIntegerField()),
                ('ultimo_seq', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sequência de Número de Processo',
                'verbose_name_plural': 'Sequências de Número de Processo',
                'db_table': 'sequencia_numero_processo',
                'constraints': [models.UniqueConstraint(fields=('ano', 'tr', 'origem'), name='uniq_seq_num_proc_chave')],
            },
        ),
    ]
