# Generated by Django 6.0.8 on 2026-09-10 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclos', '0009_fix_coordenador_column'),
        ('processos', '0010_remove_movimentacaoprocessual_antecedente_logico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poloprocessual',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polos_processuais', to='ciclos.grupotrabalho'),
        ),
    ]
