# Generated by Django 6.0.8 on 2026-09-21 21:18

from django.db import migrations, models


def limpar_pares_duplicados(apps, schema_editor):
    """
    Defesa antes da constraint: apaga o vínculo mais recente de cada par
    (processo, grupo) repetido, mantendo o mais antigo (o que ancorou eventos
    primeiro). Loga cada remoção — se isso imprimir algo, vale investigar como
    o par se duplicou, já que o fluxo de aplicar_grupos() não deveria permitir.
    """
    GrupoProcesso = apps.get_model("processos", "GrupoProcesso")

    vistos = set()
    for vinculo in GrupoProcesso.objects.order_by("pk"):
        chave = (vinculo.processo_id, vinculo.grupo_id)
        if chave in vistos:
            print(
                f"[migração 0012] removendo GrupoProcesso duplicado pk={vinculo.pk} "
                f"(processo_id={vinculo.processo_id}, grupo_id={vinculo.grupo_id})"
            )
            vinculo.delete()
        else:
            vistos.add(chave)


class Migration(migrations.Migration):

    dependencies = [
        ('ciclos', '0010_ciclosimulacao_uniq_ciclo_nome_edicao_ci_and_more'),
        ('processos', '0011_polo_processual_grupo_responsavel'),
    ]

    operations = [
        migrations.RunPython(limpar_pares_duplicados, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='grupoprocesso',
            constraint=models.UniqueConstraint(fields=('processo', 'grupo'), name='processos_grupoprocesso_uniq_processo_grupo'),
        ),
    ]
