# Generated by Django 6.0.8 on 2026-09-10 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclos', '0009_fix_coordenador_column'),
        ('movimentacoes', '0002_migrar_content_type'),
        ('processos', '0010_remove_movimentacaoprocessual_antecedente_logico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoprocessual',
            name='grupo_processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='processos.grupoprocesso'),
        ),
        migrations.AddField(
            model_name='tipomovimentacao',
            name='efeito_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipos_movimentacao', to='processos.statusprocessojudicial'),
        ),
        migrations.CreateModel(
            name='PapelAutorizadoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_simulacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciclos.cargosimulacao')),
                ('tipo_movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacoes.tipomovimentacao')),
            ],
            options={
                'db_table': 'papel_autorizado_movimentacao',
                'unique_together': {('tipo_movimentacao', 'cargo_simulacao')},
            },
        ),
        migrations.AddField(
            model_name='tipomovimentacao',
            name='papeis_autorizados',
            field=models.ManyToManyField(blank=True, related_name='tipos_movimentacao', through='movimentacoes.PapelAutorizadoMovimentacao', to='ciclos.cargosimulacao'),
        ),
        migrations.CreateModel(
            name='PreCondicaoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precondicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='movimentacoes.tipomovimentacao')),
                ('tipo_movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='movimentacoes.tipomovimentacao')),
            ],
            options={
                'db_table': 'precondicao_movimentacao',
                'unique_together': {('tipo_movimentacao', 'precondicao')},
            },
        ),
        migrations.AddField(
            model_name='tipomovimentacao',
            name='precondicoes',
            field=models.ManyToManyField(blank=True, related_name='habilita_estes', through='movimentacoes.PreCondicaoMovimentacao', through_fields=('tipo_movimentacao', 'precondicao'), to='movimentacoes.tipomovimentacao'),
        ),
        migrations.CreateModel(
            name='EfeitoColateralMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('abre_prazo', 'Abre prazo'), ('encerra_prazo', 'Encerra prazo'), ('reabre_prazo', 'Reabre prazo'), ('agenda_audiencia', 'Agenda audiência'), ('notifica', 'Notifica')], max_length=20)),
                ('tipo_movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efeitos_colaterais', to='movimentacoes.tipomovimentacao')),
            ],
            options={
                'verbose_name': 'Efeito Colateral de Movimentação',
                'verbose_name_plural': 'Efeitos Colaterais de Movimentação',
                'db_table': 'efeito_colateral_movimentacao',
                'constraints': [models.UniqueConstraint(fields=('tipo_movimentacao', 'categoria'), name='uniq_efeito_colateral_tipo_categoria')],
            },
        ),
    ]
