# Generated by Django 6.0.4 on 2026-05-22 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processos', '0008_alter_processojudicial_valor_causa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('data_feedback', models.DateTimeField(auto_now_add=True)),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='processos.movimentacaoprocessual')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks_dados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback do Professor',
                'verbose_name_plural': 'Feedbacks dos Professores',
                'db_table': 'feedback_professor',
                'ordering': ['-data_feedback'],
            },
        ),
    ]
