# Generated by Django 6.0.8 on 2026-09-14 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('processos', '0009_add_sequencia_numero_processo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feedbackprofessor',
            constraint=models.UniqueConstraint(fields=('movimentacao', 'professor'), name='uniq_feedback_por_mov_e_professor', violation_error_message='Você já avaliou esta movimentação.'),
        ),
    ]
