# Generated by Django 6.0.8 on 2026-09-14 13:12
#
# Renumerada de 0002 para 0003 no merge com a develop: as duas linhas criaram
# uma 0002 em avaliacoes. A 0002 da develop reaponta a FK `movimentacao` para
# movimentacoes.MovimentacaoProcessual, então a constraint tem de ser aplicada
# depois dela — daí a dependência direta, no lugar da antiga em processos.0009.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_alter_feedbackprofessor_movimentacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feedbackprofessor',
            constraint=models.UniqueConstraint(fields=('movimentacao', 'professor'), name='uniq_feedback_por_mov_e_professor', violation_error_message='Você já avaliou esta movimentação.'),
        ),
    ]
