"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os

from pathlib import Path

import environ


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Sem default de propósito: com um, a ausência da variável no servidor faria a
# aplicação subir silenciosamente com uma chave pública conhecida, e as
# assinaturas de sessão e de token CSRF passariam a ser forjáveis. Faltar a
# variável tem que quebrar o start.
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

# Com DEBUG=False e esta lista vazia o Django recusa toda requisição: preencher
# ALLOWED_HOSTS no .env do servidor é parte do deploy, não um detalhe opcional.
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'acesso',
    'base',
    'ciclos',
    'notificacoes',
    'processos',
    'avaliacoes',
    # `agendamentos` ainda está vazio: a audiência vive hoje em
    # `processos.Audiencia`. Fica registrado para a migração futura — remover
    # daqui se a decisão mudar.
    'agendamentos',
    'movimentacoes',
    'private_storage',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'acesso.middleware.SessionActivityMiddleware',
    'ciclos.middleware.CicloAtivoMiddleware',
    # depende de `ciclos_ativos_usuario`, populado pelo middleware acima
    'ciclos.middleware.AlunoSemCicloMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ciclos.context_processors.ciclo_ativo',
                'notificacoes.context_processors.notificacoes_usuario',
                'base.context_processors.session_timeout',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db() # Busca automaticamente as variáveis DATABASE_URL
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "usuarios.Usuario" # informa ao Django para usar o modelo de usuário personalizado

# Redirecionamentos de autenticação
LOGOUT_REDIRECT_URL = 'acesso:login' # redireciona para a página de login após logout
LOGIN_URL = 'acesso:login'
LOGIN_REDIRECT_URL = 'acesso:painel_administrativo'

# ─── Segurança ────────────────────────────────────────────────────────────────
# Padrão do Django, repetido aqui porque é a defesa contra roubo de sessão por XSS
SESSION_COOKIE_HTTPONLY = True

# Endurecimentos que só fazem sentido sob HTTPS. Derivados de DEBUG para que
# subir com DEBUG=False já traga o conjunto completo, sem depender de lembrar de
# ligar cada um no .env.
if not DEBUG:
    SESSION_COOKIE_SECURE = True    # cookie sessionid só via HTTPS
    CSRF_COOKIE_SECURE = True       # csrftoken só via HTTPS
    SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=True)
    # HSTS é a configuração mais perigosa de ligar às cegas: o navegador memoriza
    # a exigência de HTTPS pelo prazo informado e reverter exige esperar o prazo
    # (ou servir max-age=0). Comece pequeno e só aumente depois de confirmar que
    # todo o domínio serve HTTPS — 31536000 (1 ano) é o valor de regime.
    SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=3600)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True)
    SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=False)
    # Só quando a aplicação estiver atrás de um proxy/load balancer que termina
    # o TLS; ligar isto sem proxy permite forjar o cabeçalho e fingir HTTPS.
    if env.bool("BEHIND_TLS_PROXY", default=False):
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Configurações de sessão
# Tempo de inatividade em segundos antes de expirar (lido do .env, padrão 900 s = 15 min)
SESSION_COOKIE_AGE = env.int("SESSION_TIMEOUT_SECONDS", default=900)
# Sessão expira ao fechar o navegador (segurança: sem sessões persistentes no browser)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# True  → toda requisição renova o timer (timeout conta a partir da ÚLTIMA atividade)
# False → timer fixo desde o login (expira mesmo com o usuário ativo — não recomendado aqui)
SESSION_SAVE_EVERY_REQUEST = True

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'templates/static'),)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    # Carimba ?v=<mtime> nas URLs de {% static %}: sem isso o navegador
    # continua servindo o CSS/JS antigo que tem em cache.
    "staticfiles": {"BACKEND": "base.storage.StaticFilesVersionados"},
}

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# Mídia PROTEGIDA (documentos processuais)
PRIVATE_STORAGE_ROOT = os.path.join(BASE_DIR, 'arquivos_privados')
# Não é `allow_authenticated`: aquela função só pergunta se há sessão, e como o
# caminho do anexo é previsível (processos/{numero_cnj}/{arquivo}) isso entregava
# qualquer documento a qualquer usuário logado — inclusive de processo em segredo
# de justiça. A função abaixo aplica ao arquivo a mesma regra da tela do processo.
PRIVATE_STORAGE_AUTH_FUNCTION = 'processos.private_auth.pode_baixar_documento'
# Serve inline só tipos inertes e força download no resto (vide base/private_servers.py).
# Em produção atrás de nginx, trocar por 'nginx' com X-Accel-Redirect — e então o
# Content-Disposition precisa ser reposto na configuração do nginx.
PRIVATE_STORAGE_SERVER = env('PRIVATE_STORAGE_SERVER', default='base.private_servers.DocumentoProcessualServer')
# PRIVATE_STORAGE_INTERNAL_URL = '/arquivos_privados/' # necessário para nginx, mas não para django; ajustar conforme o servidor de arquivos privados

# ─── Upload de Arquivos ───────────────────────────────────────────────────────
UPLOAD_CONFIG = {
    # Tamanho máximo em MB por arquivo
    "MAX_FILE_SIZE_MB": 7,
    # Extensões permitidas (sempre em minúsculo, com ponto)
    "ALLOWED_EXTENSIONS": [".pdf", ".docx", ".jpg", ".jpeg"],
    # MIMEs reais aceitos (detectados pelos bytes do arquivo, não pelo nome)
    "ALLOWED_MIME_TYPES": [
        "application/pdf",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "image/jpeg",
    ],
    # Prefixos de MIME bloqueados mesmo que a extensão seja permitida
    "BLOCKED_MIME_PREFIXES": [
        "application/x-",           # executáveis genéricos
        "application/octet-stream", # binários arbitrários
        "text/x-",                  # scripts de shell/bat
    ],
}
