"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os

from pathlib import Path

import environ


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default='django-insecure-dev-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'acesso',
    'agendamentos',
    'base',
    'ciclos',
    'movimentacoes',
    'processos',
    'avaliacoes',
    'private_storage',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'acesso.middleware.SessionActivityMiddleware',
    'ciclos.middleware.CicloAtivoMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ciclos.context_processors.ciclo_ativo',
                'base.context_processors.session_timeout',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db() # Busca automaticamente as variáveis DATABASE_URL
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "usuarios.Usuario" # informa ao Django para usar o modelo de usuário personalizado

# Redirecionamentos de autenticação
LOGOUT_REDIRECT_URL = 'acesso:login' # redireciona para a página de login após logout
LOGIN_URL = 'acesso:login'
LOGIN_REDIRECT_URL = 'acesso:painel_administrativo'

# desconfigurações de segurança (ajustar para produção)
# SESSION_COOKIE_SECURE = True    # cookie sessionid só via HTTPS
# SESSION_COOKIE_HTTPONLY = True  # bloqueia acesso via document.cookie (XSS)
# CSRF_COOKIE_SECURE = True       # csrftoken só via HTTPS

# Configurações de sessão
# Tempo de inatividade em segundos antes de expirar (lido do .env, padrão 900 s = 15 min)
SESSION_COOKIE_AGE = env.int("SESSION_TIMEOUT_SECONDS", default=900)
# Sessão expira ao fechar o navegador (segurança: sem sessões persistentes no browser)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# True  → toda requisição renova o timer (timeout conta a partir da ÚLTIMA atividade)
# False → timer fixo desde o login (expira mesmo com o usuário ativo — não recomendado aqui)
SESSION_SAVE_EVERY_REQUEST = True

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'templates/static'),)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# Mídia PROTEGIDA (documentos processuais)
PRIVATE_STORAGE_ROOT = os.path.join(BASE_DIR, 'arquivos_privados')
PRIVATE_STORAGE_AUTH_FUNCTION = 'private_storage.permissions.allow_authenticated'
PRIVATE_STORAGE_SERVER = env('PRIVATE_STORAGE_SERVER', default='django')   # dev; em produção substituir por 'nginx' com X-Accel-Redirect
# PRIVATE_STORAGE_INTERNAL_URL = '/arquivos_privados/' # necessário para nginx, mas não para django; ajustar conforme o servidor de arquivos privados

# ─── Upload de Arquivos ───────────────────────────────────────────────────────
UPLOAD_CONFIG = {
    # Tamanho máximo em MB por arquivo
    "MAX_FILE_SIZE_MB": 7,
    # Extensões permitidas (sempre em minúsculo, com ponto)
    "ALLOWED_EXTENSIONS": [".pdf", ".docx", ".jpg", ".jpeg"],
    # MIMEs reais aceitos (detectados pelos bytes do arquivo, não pelo nome)
    "ALLOWED_MIME_TYPES": [
        "application/pdf",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "image/jpeg",
    ],
    # Prefixos de MIME bloqueados mesmo que a extensão seja permitida
    "BLOCKED_MIME_PREFIXES": [
        "application/x-",           # executáveis genéricos
        "application/octet-stream", # binários arbitrários
        "text/x-",                  # scripts de shell/bat
    ],
}
