# Generated by Django 6.0.3 on 2026-09-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aceitou_termos_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='aceitou os termos em'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='versao_termos_aceita',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='versão dos termos aceita'),
        ),
    ]
