# Generated by Django 6.0.3 on 2026-09-07 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ciclo_status_alterado', 'Mudança de status do ciclo')], max_length=50)),
                ('mensagem', models.CharField(max_length=255)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('lida', models.BooleanField(default=False)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'db_table': 'notificacao',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['destinatario', 'lida'], name='idx_notif_destinatario_lida')],
            },
        ),
    ]
