# Generated by Django 6.0.3 on 2026-09-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('ciclo_status_alterado', 'Mudança de status do ciclo'), ('movimentacao_registrada', 'Nova movimentação processual'), ('grupo_vinculado_processo', 'Grupo vinculado a um processo'), ('ciclo_coordenador_atribuido', 'Coordenador designado'), ('ciclo_participante_adicionado', 'Adicionado a um ciclo')], max_length=50),
        ),
    ]
